### ISSUE TITLE
Improve IVR telephone voting

### ISSUE THREAD

**Issue by edulix** [sequentech/ivr-lambdas#2]
# Tasks

- [ ] Use secure input in Contact Flow
- [ ] Add unit tests for AWS Lambda for vote-casting
- [ ] Use minimal permission for AWS Lambda deployment
